# Generated by Django 5.0 on 2023-12-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proofcheckerinterface", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lineitem",
            name="assumption_dependence",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="formula",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="justification",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="line_number",
            field=models.CharField(default="", max_length=255),
        ),
    ]
