# Generated by Django 5.0 on 2023-12-22 22:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("proofcheckerinterface", "0005_lineitem_unique_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lineitem",
            name="unique_id",
        ),
    ]
